--liquibase formatted sql

--changeset ggeorgiev:0118 splitStatements:false
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ('SPC Обявен за недействителен (Чл.15, т.1в - недейств. или огр. на основен патент)', 0, 'SPC Обявен за недействителен (Чл.15, т.1в - недейств. или огр. на основен патент)', 'SPC Обявен за недействителен (Чл.15, т.1в - недейств. или огр. на основен патент)', 1, '12-1562', '12');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ('SPC В срок за плащане в двоен размер на такси за влизане в сила', 0, 'SPC В срок за плащане в двоен размер на такси за влизане в сила', 'SPC В срок за плащане в двоен размер на такси за влизане в сила', 1, '12-1563', '12');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ('SPC Прекратен поради анулиране на разрешението за пускане на пазара', 0, 'SPC Прекратен поради анулиране на разрешението за пускане на пазара', 'SPC Прекратен поради анулиране на разрешението за пускане на пазара', 1, '12-1560', '12');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ('SPC Изготвено решение за отказ', 0, 'SPC Изготвено решение за отказ', 'SPC Изготвено решение за отказ', 1, '12-1397', '12');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ('SPC За публикация на оттеглена заявка (неплатени такси за публикация)', 0, 'SPC За публикация на оттеглена заявка (неплатени такси за публикация)', 'SPC За публикация на оттеглена заявка (неплатени такси за публикация)', 1, '12-1142', '12');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ('SPC За публикация на прекратяване поради неплащане на такси', 0, 'SPC За публикация на прекратяване поради неплащане на такси', 'SPC За публикация на прекратяване поради неплащане на такси', 1, '12-1140', '12');


update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ПМ Действащ – в срок за продължаване след плащане в двоен размер', bpo_online_status_en='ПМ Действащ – в срок за продължаване с глоба', backoffice_status_name='ПМ Действащ – в срок за продължаване след плащане в двоен размер' where code='11-1031';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC В срок за отстраняване на недостатъци', bpo_online_status_en='SPC В срок за отстраняване на недостатъци', backoffice_status_name='SPC В срок за отстраняване на недостатъци' where code='12-309';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC В срок за плащане на такси за издаване в двоен размер', bpo_online_status_en='SPC В Експертиза', backoffice_status_name='SPC В срок за плащане на такси за издаване в двоен размер' where code='12-341';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC За издаване на защитен сертификат', bpo_online_status_en='SPC За издаване на защитен сертификат', backoffice_status_name='SPC За издаване на защитен сертификат' where code='12-345';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ПМ За Експертно заключение', bpo_online_status_en='без достъп', backoffice_status_name='ПМ За Експертно заключение' where code='11-320';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Отказана заявка след публикация', bpo_online_status_en='SPC Отказана заявка след публикация', backoffice_status_name='SPC Отказана заявка след публикация' where code='12-359';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Всрок за възражение', bpo_online_status_en='SPC Всрок за възражение', backoffice_status_name='SPC В срок за възражение' where code='17-866';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Недатирана (неполучен оригинал)', bpo_online_status_en='SPC Недатирана (неполучен оригинал)', backoffice_status_name='SPC Недатирана (неполучен оригинал)' where code='12-303';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC В срок за плащане на такси', bpo_online_status_en='SPC В срок за плащане на такси', backoffice_status_name='SPC В срок за плащане на такси' where code='12-305';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Проверка за платени такси', bpo_online_status_en='SPC Проверка за платени такси', backoffice_status_name='SPC Проверка за платени такси' where code='12-294';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Отменено решение', bpo_online_status_en='SPC Отменено решение', backoffice_status_name='SPC Отменено решение' where code='12-860';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Получен оригинал след срок', bpo_online_status_en='SPC Получен оригинал след срок', backoffice_status_name='SPC Получен оригинал след срок' where code='12-304';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ПТ Действащ патент - в срок за плащане в двоен размер', bpo_online_status_en='ПТ Действащ патент - в срок за плащане с глоба', backoffice_status_name='ПТ Действащ патент - в срок за плащане в двоен размер' where code='10-776';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Формална експертиза', bpo_online_status_en='SPC Формална експертиза', backoffice_status_name='SPC Формална експертиза' where code='12-299';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Изтекъл срок за плащане на такси', bpo_online_status_en='SPC Изтекъл срок за плащане на такси', backoffice_status_name='SPC Изтекъл срок за плащане на такси' where code='12-297';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Проверка за установяване на на дата на подаване', bpo_online_status_en='SPC Проверка за установяване на на дата на подаване', backoffice_status_name='SPC Проверка за установяване на на дата на подаване' where code='12-292';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Изтекъл срок за възражение', bpo_online_status_en='SPC Изтекъл срок за възражение', backoffice_status_name='SPC Изтекъл срок за възражение' where code='12-858';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Спряно производство чл.6 ал.5', bpo_online_status_en='SPC В Експертиза', backoffice_status_name='SPC Спряно производство чл.6 ал.5' where code='12-363';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Изчакване на оригинал', bpo_online_status_en='SPC Изчакване на оригинал', backoffice_status_name='SPC Изчакване на оригинал' where code='12-300';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ПТ За Експертно заключение', bpo_online_status_en='без достъп', backoffice_status_name='ПТ За Експертно заключение' where code='10-327';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ПТ В срок за заплащане на такси в двоен размер', bpo_online_status_en='без достъп', backoffice_status_name='ПТ В срок за заплащане на такси в двоен размер' where code='10-958';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC  Удължен срок за отказ', bpo_online_status_en='SPC  Удължен срок за отказ', backoffice_status_name='SPC Удължен срок за отказ' where code='17-514';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ПТ Неиздаден поради неплащане', bpo_online_status_en='ПТ Неиздаден поради неплащане', backoffice_status_name='ПТ Неиздаден поради неплащане' where code='10-979';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Спряно производство по искане на заявителя', bpo_online_status_en='SPC Спряно производство по искане на заявителя', backoffice_status_name='SPC Спряно производство по искане на заявителя' where code='12-1136';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ПМ За Експертно заключение', bpo_online_status_en='без достъп', backoffice_status_name='ПМ За Експертно заключение' where code='11-321';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Получен оригинал', bpo_online_status_en='SPC Получен оригинал', backoffice_status_name='SPC Получен оригинал' where code='12-302';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ПТ В срок за заплащане на такси в двоен размер', bpo_online_status_en='ПТ В Експертиза', backoffice_status_name='ПТ В срок за заплащане на такси в двоен размер' where code='10-233';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'без достъп', bpo_online_status_en='без достъп', backoffice_status_name='(old) SPC Формална експертиза не е ОК ' where code='12-307';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Изтекъл срок за получаване на оригинал', bpo_online_status_en='SPC Изтекъл срок за получаване на оригинал', backoffice_status_name='SPC Изтекъл срок за получаване на оригинал' where code='12-301';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Недатирана заявка', bpo_online_status_en='SPC Недатирана заявка', backoffice_status_name='SPC Недатирана заявка' where code='12-337';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'без достъп', bpo_online_status_en='без достъп', backoffice_status_name='(old) SPC Платени такси' where code='12-295';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC В срок за отстраняване на недостатъци по документи', bpo_online_status_en='SPC В срок за отстраняване на недостатъци по документи', backoffice_status_name='SPC В срок за отстраняване на недостатъци по документи' where code='12-293';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Изтекъл срок за отстраняване на недостатъци', bpo_online_status_en='SPC Изтекъл срок за отстраняване на недостатъци', backoffice_status_name='SPC Изтекъл срок за отстраняване на недостатъци' where code='12-310';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC За оттегляне на заявка', bpo_online_status_en='SPC За оттегляне на заявка', backoffice_status_name='SPC За оттегляне на заявка' where code='12-347';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC За отказ', bpo_online_status_en='SPC За отказ', backoffice_status_name='SPC За отказ' where code='12-357';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Оттеглена заявка поради неплатени такси', bpo_online_status_en='SPC Оттеглена заявка поради неплатени такси', backoffice_status_name='SPC Оттеглена заявка поради неплатени такси' where code='12-298';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC За решение', bpo_online_status_en='SPC За решение', backoffice_status_name='SPC За решение' where code='12-313';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Обявен за недействителен (Чл.15, т.1а - издаден в противоречие с чл.3)', bpo_online_status_en='SPC Обявен за недействителен (Чл.15, т.1а - издаден в противоречие с чл.3)', backoffice_status_name='SPC Обявен за недействителен (Чл.15, т.1а - издаден в противоречие с чл.3)' where code='12-1222';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC В срок за възражение', bpo_online_status_en='SPC В срок за възражение', backoffice_status_name='SPC В срок за възражение' where code='12-857';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Постъпило възражение', bpo_online_status_en='SPC Постъпило възражение', backoffice_status_name='SPC Постъпило възражение' where code='12-859';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ПМ В срок за плащане на такси в двоен размер', bpo_online_status_en='ПМ В срок за плащане на такси с глоба', backoffice_status_name='ПМ В срок за плащане на такси в двоен размер' where code='11-1294';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC В срок за плащане на такси', bpo_online_status_en='SPC В срок за плащане на такси', backoffice_status_name='SPC В срок за плащане на такси' where code='12-296';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Изтекъл срок такси за публикация', bpo_online_status_en='SPC Изтекъл срок такси за публикация', backoffice_status_name='SPC Изтекъл срок такси за публикация' where code='12-311';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC За съобщение по несъответствия', bpo_online_status_en='SPC За съобщение по несъответствия', backoffice_status_name='SPC За съобщение по несъответствия' where code='12-317';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ПТ За Експертно заключение', bpo_online_status_en='без достъп', backoffice_status_name='ПТ За Експертно заключение' where code='10-329';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Оттеглена заявка чл.3/чл.6', bpo_online_status_en='SPC Оттеглена заявка чл.3/чл.6', backoffice_status_name='SPC Оттеглена заявка чл.3/чл.6' where code='12-365';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Оттеглена заявка (неплатени такси за публикация)', bpo_online_status_en='SPC Оттеглена заявка (неплатени такси за публикация)', backoffice_status_name='SPC Оттеглена заявка (неплатени такси за публикация)' where code='12-312';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'SPC Отказана заявка преди публикация', bpo_online_status_en='SPC Отказана заявка преди публикация', backoffice_status_name='SPC Отказана заявка преди публикация' where code='12-308';


INSERT INTO nomenclatures.backoffice_patent_status_map(backoffice_status_code, fo_status_code) VALUES ('12-1140', 'Pending');
INSERT INTO nomenclatures.backoffice_patent_status_map(backoffice_status_code, fo_status_code) VALUES ('12-1142', 'Pending');
INSERT INTO nomenclatures.backoffice_patent_status_map(backoffice_status_code, fo_status_code) VALUES ('12-1397', 'Pending');
INSERT INTO nomenclatures.backoffice_patent_status_map(backoffice_status_code, fo_status_code) VALUES ('12-1560', 'Lapsed');
INSERT INTO nomenclatures.backoffice_patent_status_map(backoffice_status_code, fo_status_code) VALUES ('12-1562', 'Lapsed');
INSERT INTO nomenclatures.backoffice_patent_status_map(backoffice_status_code, fo_status_code) VALUES ('12-1563', 'Pending');


update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'без достъп', bpo_online_status_en='без достъп', backoffice_status_name='ПД Изпратено съобщение за плащане на такси' where code='15-1316';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'без достъп', bpo_online_status_en='без достъп', backoffice_status_name='ПД Изпратено съобщение за отстраняване на недостатъци' where code='15-1317';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'без достъп', bpo_online_status_en='без достъп', backoffice_status_name='ПД Изпратено уведомление за такси за регистрация' where code='15-1318';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'без достъп', bpo_online_status_en='без достъп', backoffice_status_name='ПД Генериран регистров номер' where code='15-1342';

INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ПД Изпратено предварително становище за отказ',1, 'без достъп', 'без достъп',1,'15-1319', '15');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ПД Присъединен към друга заявка',1, 'без достъп', 'без достъп',0,'15-1354', '15');


INSERT INTO nomenclatures.backoffice_dsview_status_map (backoffice_status_code, dsview_list_code, dsview_detailed_code, dsview_detailed_code_bg, deferred_publication) VALUES ('15-1319', null, null, null, 0);
INSERT INTO nomenclatures.backoffice_dsview_status_map (backoffice_status_code, dsview_list_code, dsview_detailed_code, dsview_detailed_code_bg, deferred_publication) VALUES ('15-1354', null, null, null, 0);



update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Прекратен след публикация B2/B3', bpo_online_status_en='EP lapsed after B2 publication', backoffice_status_name='ЕП Прекратен след публикация B2/B3' where code='14-1020';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Действащ патент - в срок за плащане в двоен размер', bpo_online_status_en='EP valid on the territory of Bulgaria', backoffice_status_name='ЕП Действащ патент - в срок за плащане в двоен размер' where code='14-1042';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Променен след публикация B2/B3 - изчакване за валидиране', bpo_online_status_en='EP ammended after B2 publication - pending validation', backoffice_status_name='ЕП Променен след публикация B2/B3 - изчакване за валидиране' where code='14-1126';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='ЕП За издаване на сертификат', backoffice_status_name='ЕП За издаване на сертификат' where code='14-1289';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='ЕП Изпратено съобщение за недостатъци', backoffice_status_name='ЕП Изпратено съобщение за недостатъци' where code='14-1297';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Application keyed in', backoffice_status_name='ЕП Въведено искане' where code='14-368';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Documents and fees check', backoffice_status_name='ЕП Проверка за документи и такси' where code='14-370';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Originals expected', backoffice_status_name='ЕП Изчакване на подписан оригинал' where code='14-371';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Originals provision deadline expired', backoffice_status_name='ЕП Изтекъл срок за получаване на оригинал' where code='14-372';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Originals provided on time', backoffice_status_name='ЕП Получен оригинал в срок' where code='14-373';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП за публикация Т1', bpo_online_status_en='EP for T1 Publication', backoffice_status_name='ЕП За публикация Т1' where code='14-376';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Deficiencies corrected', backoffice_status_name='ЕП В срок за отстраняване на недостатъци' where code='14-377';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Deadline for deficiencies correction expired', backoffice_status_name='ЕП Изтекъл срок за отстраняване на недостатъци' where code='14-378';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Искане в производство', bpo_online_status_en='EP Validation request', backoffice_status_name='ЕП Искане за валидиране' where code='14-382';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП За публикация Т3', bpo_online_status_en='EP T3 Publication', backoffice_status_name='ЕП За публикация Т3' where code='14-383';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Прекратен поради неплащане на годишни такси', bpo_online_status_en='EP Cancelled due to annuities not paid', backoffice_status_name='ЕП Прекратен поради неплащане на годишни такси' where code='14-856';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ЕП Проверка за документи и такси след публикция B2/B3', bpo_online_status_en='EP Documents and fees check after B2 publication', backoffice_status_name='ЕП Проверка за документи и такси след публикция B2/B3' where code='14-1149';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ЕП С единно действие', bpo_online_status_en='Unitary patent', backoffice_status_name='ЕП С единно действие' where code='14-1575';

update nomenclatures.backoffice_epopatent_status_map set ep_status_code = 'NO_STATUS_18', fep_inval_date_tag = null where backoffice_status_code='14-1019';
INSERT INTO nomenclatures.backoffice_epopatent_status_map (backoffice_status_code, ep_status_code, fep_inval_date_tag) VALUES ('14-1454','N/A', null);
INSERT INTO nomenclatures.backoffice_epopatent_status_map (backoffice_status_code, ep_status_code, fep_inval_date_tag) VALUES ('14-1575','N/A', null);



update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'TM Формална експертиза', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Формални недостатъци' where code='2-020';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'TM Формална експертиза', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Изтекъл срок за отстраняване на формални недостатъци' where code='2-021';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Предварителен пълен отказ' where code='2-022';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Отказана регистрация', bpo_online_status_en='ТМ Отказана заявка', backoffice_status_name='ТМ Пълен отказ' where code='2-023';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Предварителен частичен отказ' where code='2-024';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Изтекъл срок за отговор на частичен отказ' where code='2-025';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Решение за частичен отказ (в срок за разделяне на заявката)' where code='2-026';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Изтекъл срок за разделяне' where code='2-027';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Изчакване за обжалване на решение за частичен отказ' where code='2-029';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Изтекъл срок за обжалване на частичен отказ' where code='2-030';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Обжалвано решение за частичен отказ', bpo_online_status_en='ТМ Подадена жалба', backoffice_status_name='ТМ Обжалван частичен отказ' where code='2-031';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Разделена заявка' where code='2-032';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Регистрирана', bpo_online_status_en='ТМ Регистрирана', backoffice_status_name='ТМ За потвърждаване на регистрация' where code='2-033';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'TM Формална експертиза', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Удължен срок за отговор по формални недостатъци' where code='2-035';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Удължен срок за отговор на пълен отказ' where code='2-036';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Удължен срок за отговор на частичен отказ' where code='2-037';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Изтекъл срок за отговор на пълен отказ' where code='2-038';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Образувано производство по опозиция', bpo_online_status_en='ТМ Образувано производство по опозиция', backoffice_status_name='(old) ТМ Образувано производство по опозиция' where code='4-056';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Отхвърляне на опозиция', bpo_online_status_en='ТМ Отхвърляне на опозиция', backoffice_status_name='(old) ТМ Отхвърляне на опозиция' where code='4-059';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Частичен отказ след опозиция', bpo_online_status_en='ТМ Частичен отказ след опозиция', backoffice_status_name='(old) ТМ Частичен отказ след опозиция' where code='4-060';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Пълен отказ след опозиция', bpo_online_status_en='ТМ Пълен отказ след опозиция', backoffice_status_name='(old) ТМ Пълен отказ след опозиция' where code='4-061';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Необразувано производство по опозиция (чл. 38в, ал. 2)', bpo_online_status_en='ТМ Необразувано производство по опозиция (чл. 38в, ал. 2)', backoffice_status_name='(old) ТМ Необразувано производство по опозиция (чл. 38в, ал. 2) ' where code='4-063';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Формално нередовна опозиция', bpo_online_status_en='ТМ Формално нередовна опозиция', backoffice_status_name='(old) ТМ Формално нередовна опозиция ' where code='4-064';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Прекратено производство по опозиция (чл.38в, ал.3)', bpo_online_status_en='ТМ Прекратено производство по опозиция (чл.38в, ал.3)', backoffice_status_name='(old) ТМ Прекратено производство по опозиция (чл.38в, ал.3) ' where code='4-068';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Прекратено производство (чл. 38г, ал. 3)', bpo_online_status_en='ТМ Прекратено производство (чл. 38г, ал. 3)', backoffice_status_name='(old) ТМ Прекратено производство (чл. 38г, ал. 3) ' where code='4-071';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Първи продължен срок за споразумение', bpo_online_status_en='ТМ Първи продължен срок за споразумение', backoffice_status_name='(old) ТМ Първи продължен срок за споразумение' where code='4-073';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Втори продължен срок за споразумение', bpo_online_status_en='ТМ Втори продължен срок за споразумение', backoffice_status_name='(old) ТМ Втори продължен срок за споразумение' where code='4-076';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Изтекъл първи продължен срок', bpo_online_status_en='ТМ Изтекъл първи продължен срок', backoffice_status_name='(old) ТМ Изтекъл първи продължен срок' where code='4-077';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Изтекъл втори продължен срок', bpo_online_status_en='ТМ Изтекъл втори продължен срок', backoffice_status_name='(old) ТМ Изтекъл втори продължен срок' where code='4-078';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ В срок за доказване на реално използване', bpo_online_status_en='ТМ В срок за доказване на реално използване', backoffice_status_name='(old) ТМ В срок за доказване на реално използване' where code='4-083';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Оттегляне на заявка', bpo_online_status_en='ТМ Оттегляне на заявка', backoffice_status_name='(old) ТМ Оттегляне на заявка' where code='4-084';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Прекратено производство поради оттеглена опозиция', bpo_online_status_en='ТМ Прекратено производство поради оттеглена опозиция', backoffice_status_name='(old) ТМ Прекратено производство поради оттеглена опозиция' where code='4-085';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Прекратено производство (отпаднал предмет)', bpo_online_status_en='ТМ Прекратено производство (отпаднал предмет)', backoffice_status_name='(old) ТМ Прекратено производство (отпаднал предмет)' where code='4-090';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Прекратено производство (чл. 14, ал. 3)', bpo_online_status_en='ТМ Прекратено производство (чл. 14, ал. 3)', backoffice_status_name='(old) ТМ Прекратено производство (чл. 14, ал. 3)' where code='4-091';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Изтекъл срок за доказване на използване', bpo_online_status_en='ТМ Изтекъл срок за доказване на използване', backoffice_status_name='(old) ТМ Изтекъл срок за доказване на използване' where code='4-092';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Продължен срок за доказване на използване', bpo_online_status_en='ТМ Продължен срок за доказване на използване', backoffice_status_name='(old) ТМ Продължен срок за доказване на използване' where code='4-093';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Изтекъл продължен срок', bpo_online_status_en='ТМ Изтекъл продължен срок', backoffice_status_name='(old) ТМ Изтекъл продължен срок' where code='4-094';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Отхвърлена опозиция (чл. 38г, ал. 6)', bpo_online_status_en='ТМ Отхвърлена опозиция (чл. 38г, ал. 6)', backoffice_status_name='(old) ТМ Отхвърлена опозиция (чл. 38г, ал. 6)' where code='4-095';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ В срок за становище по доказателства', bpo_online_status_en='ТМ В срок за становище по доказателства', backoffice_status_name='(old) ТМ В срок за становище по доказателства' where code='4-096';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Изтекъл срок за становище по доказателства', bpo_online_status_en='ТМ Изтекъл срок за становище по доказателства', backoffice_status_name='(old) ТМ Изтекъл срок за становище по доказателства' where code='4-097';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Прекратено производство (чл. 14, ал. 4)', bpo_online_status_en='ТМ Прекратено производство (чл. 14, ал. 4)', backoffice_status_name='(old) ТМ Прекратено производство (чл. 14, ал. 4)' where code='4-098';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Спряно производство - служебно (чл. 38д, ал. 2)', bpo_online_status_en='ТМ Спряно производство - служебно (чл. 38д, ал. 2)', backoffice_status_name='(old) ТМ Спряно производство - служебно (чл. 38д, ал. 2)' where code='4-099';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Регистрирана', bpo_online_status_en='ТМ Регистрирана', backoffice_status_name='ТМ За издаване на свидетелство' where code='2-019';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Подадена Заявка', bpo_online_status_en='ТМ Подадена Заявка', backoffice_status_name='ТМ Подадена Заявка' where code='2-003';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'TM Формална експертиза', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Формална експертиза' where code='2-007';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Отказана регистрация', bpo_online_status_en='ТМ Отказана регистрация на заявка', backoffice_status_name='ТМ Отказана' where code='2-009';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ Експертиза по същество' where code='2-013';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ Експертиза по същество', bpo_online_status_en='ТМ Подадена заявка', backoffice_status_name='ТМ За публикация на заявена марка' where code='2-014';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ В срок за опозиция и възражение', bpo_online_status_en='ТМ В срок за опозиция и възражение', backoffice_status_name='ТМ В срок за опозиция и възражение' where code='2-015';
update nomenclatures.backoffice_status_map set for_deletion = 0, bpo_online_status = 'ТМ За регистрация', bpo_online_status_en='ТМ За регистрация', backoffice_status_name='ТМ За регистрация' where code='2-016';
update nomenclatures.backoffice_status_map set for_deletion = 1, bpo_online_status = 'ТМ Действия по всяко време', bpo_online_status_en='TM Dummy Status', backoffice_status_name='ТМ Действия по всяко време' where code='2-039';


INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изпратено решение за спиране на производство по искане на заявителя',0, 'ТМ Изпратено решение за спиране на производство по искане на заявителя', 'ТМ Изпратено решение за спиране на производство по искане на заявителя',0,'2-1590', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Спряно производство по искане на заявителя - в срок за обжалване ',0, 'ТМ Спряно производство по искане на заявителя - в срок за обжалване ', 'ТМ Спряно производство по искане на заявителя - в срок за обжалване ',0,'2-1591', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Обжалвано решение/определение за спиране по искане на заявителя',0, 'ТМ Обжалвано решение/определение за спиране по искане на заявителя', 'ТМ Обжалвано решение/определение за спиране по искане на заявителя',0,'2-1592', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Спряно производство по искане на заявителя',0, 'ТМ Спряно производство по искане на заявителя', 'ТМ Спряно производство по искане на заявителя',0,'2-1594', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изпратено решение за оттегляне поради неплатени такси',0, 'ТМ Изпратено решение за оттегляне поради неплатени такси', 'ТМ Изпратено решение за оттегляне поради неплатени такси',0,'2-1595', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ В срок за обжалване на решение за оттегляне поради неплатени такси',0, 'ТМ В срок за обжалване на решение за оттегляне поради неплатени такси', 'ТМ В срок за обжалване на решение за оттегляне поради неплатени такси',0,'2-1596', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Обжалвано решение за оттегляне поради неплатени такси',0, 'ТМ Обжалвано решение за оттегляне поради неплатени такси', 'ТМ Обжалвано решение за оттегляне поради неплатени такси',0,'2-1597', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изпратено съобщение за преобразуване',0, 'ТМ Изпратено съобщение за преобразуване', 'ТМ Изпратено съобщение за преобразуване',0,'2-1600', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ В срок за преобразуване',0, 'ТМ В срок за преобразуване', 'ТМ В срок за преобразуване',0,'2-1601', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Прекратено производство по преобразуване',0, 'ТМ Прекратено производство по преобразуване', 'ТМ Прекратено производство по преобразуване',0,'2-1602', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Проверка за допустимост на разделяне',0, 'ТМ Проверка за допустимост на разделяне', 'ТМ Проверка за допустимост на разделяне',0,'2-1603', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изпратено уведомление за нередовности по разделянето',0, 'ТМ Изпратено уведомление за нередовности по разделянето', 'ТМ Изпратено уведомление за нередовности по разделянето',0,'2-1604', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Връчено уведомление за нередовности по разделянето',0, 'ТМ Връчено уведомление за нередовности по разделянето', 'ТМ Връчено уведомление за нередовности по разделянето',0,'2-1605', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изпратено решение за прекратяване на производство по преобразуване',0, 'ТМ За преобразуване на марка на ЕС в национална', 'ТМ За преобразуване на марка на ЕС в национална',0,'2-1360', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ В срок за обжалване на прекратяване на производство по преобразуване',0, 'ТМ За преобразуване на марка на ЕС в национална', 'ТМ За преобразуване на марка на ЕС в национална',0,'2-1361', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изтекъл срок за обжалване на прекратяване на производство по преобразуване',0, 'ТМ За преобразуване на марка на ЕС в национална', 'ТМ За преобразуване на марка на ЕС в национална',0,'2-1362', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изтекъл срок за отстраняване на нередовности по разделянето',0, 'ТМ Изтекъл срок за отстраняване на нередовности по разделянето', 'ТМ Изтекъл срок за отстраняване на нередовности по разделянето',0,'2-1606', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Решение за разделяне на заявка',0, 'ТМ Решение за разделяне на заявка', 'ТМ Решение за разделяне на заявка',0,'2-1607', '2');
INSERT INTO nomenclatures.backoffice_status_map (backoffice_status_name, for_deletion, bpo_online_status, bpo_online_status_en, show_expiration_date, code, process_type) VALUES ( 'ТМ Изтекъл срок за преобразуване',0, 'ТМ Изтекъл срок за преобразуване', 'ТМ Изтекъл срок за преобразуване',0,'2-1608', '2');


UPDATE nomenclatures.backoffice_tmview_status_map set tmview_detailed_code='Application refused', tmview_detailed_code_bg='Отказана регистрация', tmview_list_code='Ended',show_person_missing_publication=0 where backoffice_status_code='2-009';
UPDATE nomenclatures.backoffice_tmview_status_map set tmview_detailed_code='Application refused', tmview_detailed_code_bg='Отказана регистрация', tmview_list_code='Ended',show_person_missing_publication=1 where backoffice_status_code='2-834';
UPDATE nomenclatures.backoffice_tmview_status_map set tmview_detailed_code='Registration cancelled', tmview_detailed_code_bg='Отказана регистрация', tmview_list_code='Ended',show_person_missing_publication=1 where backoffice_status_code='2-839';

INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1590');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1591');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1592');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1594');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1595');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1596');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1597');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1600');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1601');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1602');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1603');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1604');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1605');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1360');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1361');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1362');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1606');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1607');
INSERT INTO  nomenclatures.backoffice_tmview_status_map (tmview_detailed_code, tmview_detailed_code_bg, tmview_list_code, show_person_missing_publication, backoffice_status_code) VALUES ('Application filed','ТМ Подадена заявка', 'Filed',0, '2-1608');
