//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AddressStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CityNameEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AddressStreetEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressPostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressCityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CorrespondenceAddressCityNameEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
    "countryCode",
    "cityName",
    "addressStreet",
    "postalCode",
    "cityNameEn",
    "addressStreetEn",
    "phone",
    "email",
    "website",
    "correspondenceAddress",
    "correspondenceAddressEn",
    "correspondenceAddressPostalCode",
    "correspondenceAddressPhone",
    "correspondenceAddressEmail",
    "correspondenceAddressFax",
    "correspondenceAddressCityName",
    "correspondenceAddressCityNameEn"
})
public class AddressType {

    @XmlElement(name = "CountryCode")
    protected String countryCode;
    @XmlElement(name = "CityName")
    protected String cityName;
    @XmlElement(name = "AddressStreet")
    protected String addressStreet;
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    @XmlElement(name = "CityNameEn")
    protected String cityNameEn;
    @XmlElement(name = "AddressStreetEn")
    protected String addressStreetEn;
    @XmlElement(name = "Phone")
    protected String phone;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "Website")
    protected String website;
    @XmlElement(name = "CorrespondenceAddress")
    protected String correspondenceAddress;
    @XmlElement(name = "CorrespondenceAddressEn")
    protected String correspondenceAddressEn;
    @XmlElement(name = "CorrespondenceAddressPostalCode")
    protected String correspondenceAddressPostalCode;
    @XmlElement(name = "CorrespondenceAddressPhone")
    protected String correspondenceAddressPhone;
    @XmlElement(name = "CorrespondenceAddressEmail")
    protected String correspondenceAddressEmail;
    @XmlElement(name = "CorrespondenceAddressFax")
    protected String correspondenceAddressFax;
    @XmlElement(name = "CorrespondenceAddressCityName")
    protected String correspondenceAddressCityName;
    @XmlElement(name = "CorrespondenceAddressCityNameEn")
    protected String correspondenceAddressCityNameEn;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityName(String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the addressStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStreet() {
        return addressStreet;
    }

    /**
     * Sets the value of the addressStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStreet(String value) {
        this.addressStreet = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the cityNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityNameEn() {
        return cityNameEn;
    }

    /**
     * Sets the value of the cityNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityNameEn(String value) {
        this.cityNameEn = value;
    }

    /**
     * Gets the value of the addressStreetEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStreetEn() {
        return addressStreetEn;
    }

    /**
     * Sets the value of the addressStreetEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStreetEn(String value) {
        this.addressStreetEn = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the correspondenceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddress() {
        return correspondenceAddress;
    }

    /**
     * Sets the value of the correspondenceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddress(String value) {
        this.correspondenceAddress = value;
    }

    /**
     * Gets the value of the correspondenceAddressEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressEn() {
        return correspondenceAddressEn;
    }

    /**
     * Sets the value of the correspondenceAddressEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressEn(String value) {
        this.correspondenceAddressEn = value;
    }

    /**
     * Gets the value of the correspondenceAddressPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressPostalCode() {
        return correspondenceAddressPostalCode;
    }

    /**
     * Sets the value of the correspondenceAddressPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressPostalCode(String value) {
        this.correspondenceAddressPostalCode = value;
    }

    /**
     * Gets the value of the correspondenceAddressPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressPhone() {
        return correspondenceAddressPhone;
    }

    /**
     * Sets the value of the correspondenceAddressPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressPhone(String value) {
        this.correspondenceAddressPhone = value;
    }

    /**
     * Gets the value of the correspondenceAddressEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressEmail() {
        return correspondenceAddressEmail;
    }

    /**
     * Sets the value of the correspondenceAddressEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressEmail(String value) {
        this.correspondenceAddressEmail = value;
    }

    /**
     * Gets the value of the correspondenceAddressFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressFax() {
        return correspondenceAddressFax;
    }

    /**
     * Sets the value of the correspondenceAddressFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressFax(String value) {
        this.correspondenceAddressFax = value;
    }

    /**
     * Gets the value of the correspondenceAddressCityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressCityName() {
        return correspondenceAddressCityName;
    }

    /**
     * Sets the value of the correspondenceAddressCityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressCityName(String value) {
        this.correspondenceAddressCityName = value;
    }

    /**
     * Gets the value of the correspondenceAddressCityNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespondenceAddressCityNameEn() {
        return correspondenceAddressCityNameEn;
    }

    /**
     * Sets the value of the correspondenceAddressCityNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespondenceAddressCityNameEn(String value) {
        this.correspondenceAddressCityNameEn = value;
    }

}
