//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CivilIdKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="CivilIdKindType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="NATIONAL_ID"/&gt;
 *     &lt;enumeration value="FOREIGN_ID"/&gt;
 *     &lt;enumeration value="PERSONAL_DOCUMENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CivilIdKindType")
@XmlEnum
public enum CivilIdKindType {

    NATIONAL_ID,
    FOREIGN_ID,
    PERSONAL_DOCUMENT;

    public String value() {
        return name();
    }

    public static CivilIdKindType fromValue(String v) {
        return valueOf(v);
    }

}
