//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryRepresentativeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryRepresentativeDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RepresentativeCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="FormattedNameAddress" type="{http://www.bpo.bg/schema/represent/history}FormattedNameAddressType" minOccurs="0"/&gt;
 *         &lt;element name="CivilIdKind" type="{http://www.bpo.bg/schema/represent/history}CivilIdKindType" minOccurs="0"/&gt;
 *         &lt;element name="CivilId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdCardIssueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DiplomaSpeciality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DiplomaSpecialityEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IpObjects" type="{http://www.bpo.bg/schema/represent/history}IpObjectsType" minOccurs="0"/&gt;
 *         &lt;element name="QualificationCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LivingAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryRepresentativeDataType", propOrder = {
    "representativeCode",
    "formattedNameAddress",
    "civilIdKind",
    "civilId",
    "idCardNumber",
    "idCardIssueDate",
    "diplomaSpeciality",
    "diplomaSpecialityEn",
    "ipObjects",
    "qualificationCountryCode",
    "livingAddress"
})
public class HistoryRepresentativeDataType {

    @XmlElement(name = "RepresentativeCode")
    protected BigInteger representativeCode;
    @XmlElement(name = "FormattedNameAddress")
    protected FormattedNameAddressType formattedNameAddress;
    @XmlElement(name = "CivilIdKind")
    @XmlSchemaType(name = "token")
    protected CivilIdKindType civilIdKind;
    @XmlElement(name = "CivilId")
    protected String civilId;
    @XmlElement(name = "IdCardNumber")
    protected String idCardNumber;
    @XmlElement(name = "IdCardIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar idCardIssueDate;
    @XmlElement(name = "DiplomaSpeciality")
    protected String diplomaSpeciality;
    @XmlElement(name = "DiplomaSpecialityEn")
    protected String diplomaSpecialityEn;
    @XmlElement(name = "IpObjects")
    @XmlSchemaType(name = "token")
    protected IpObjectsType ipObjects;
    @XmlElement(name = "QualificationCountryCode")
    protected String qualificationCountryCode;
    @XmlElement(name = "LivingAddress")
    protected String livingAddress;

    /**
     * Gets the value of the representativeCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRepresentativeCode() {
        return representativeCode;
    }

    /**
     * Sets the value of the representativeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRepresentativeCode(BigInteger value) {
        this.representativeCode = value;
    }

    /**
     * Gets the value of the formattedNameAddress property.
     * 
     * @return
     *     possible object is
     *     {@link FormattedNameAddressType }
     *     
     */
    public FormattedNameAddressType getFormattedNameAddress() {
        return formattedNameAddress;
    }

    /**
     * Sets the value of the formattedNameAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormattedNameAddressType }
     *     
     */
    public void setFormattedNameAddress(FormattedNameAddressType value) {
        this.formattedNameAddress = value;
    }

    /**
     * Gets the value of the civilIdKind property.
     * 
     * @return
     *     possible object is
     *     {@link CivilIdKindType }
     *     
     */
    public CivilIdKindType getCivilIdKind() {
        return civilIdKind;
    }

    /**
     * Sets the value of the civilIdKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link CivilIdKindType }
     *     
     */
    public void setCivilIdKind(CivilIdKindType value) {
        this.civilIdKind = value;
    }

    /**
     * Gets the value of the civilId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCivilId() {
        return civilId;
    }

    /**
     * Sets the value of the civilId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCivilId(String value) {
        this.civilId = value;
    }

    /**
     * Gets the value of the idCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * Sets the value of the idCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCardNumber(String value) {
        this.idCardNumber = value;
    }

    /**
     * Gets the value of the idCardIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIdCardIssueDate() {
        return idCardIssueDate;
    }

    /**
     * Sets the value of the idCardIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIdCardIssueDate(XMLGregorianCalendar value) {
        this.idCardIssueDate = value;
    }

    /**
     * Gets the value of the diplomaSpeciality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiplomaSpeciality() {
        return diplomaSpeciality;
    }

    /**
     * Sets the value of the diplomaSpeciality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiplomaSpeciality(String value) {
        this.diplomaSpeciality = value;
    }

    /**
     * Gets the value of the diplomaSpecialityEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiplomaSpecialityEn() {
        return diplomaSpecialityEn;
    }

    /**
     * Sets the value of the diplomaSpecialityEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiplomaSpecialityEn(String value) {
        this.diplomaSpecialityEn = value;
    }

    /**
     * Gets the value of the ipObjects property.
     * 
     * @return
     *     possible object is
     *     {@link IpObjectsType }
     *     
     */
    public IpObjectsType getIpObjects() {
        return ipObjects;
    }

    /**
     * Sets the value of the ipObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpObjectsType }
     *     
     */
    public void setIpObjects(IpObjectsType value) {
        this.ipObjects = value;
    }

    /**
     * Gets the value of the qualificationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualificationCountryCode() {
        return qualificationCountryCode;
    }

    /**
     * Sets the value of the qualificationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualificationCountryCode(String value) {
        this.qualificationCountryCode = value;
    }

    /**
     * Gets the value of the livingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLivingAddress() {
        return livingAddress;
    }

    /**
     * Sets the value of the livingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLivingAddress(String value) {
        this.livingAddress = value;
    }

}
