//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice minOccurs="0"&gt;
 *         &lt;element name="HistoryPartnershipData" type="{http://www.bpo.bg/schema/represent/history}HistoryPartnershipDataType"/&gt;
 *         &lt;element name="HistoryRepresentativeData" type="{http://www.bpo.bg/schema/represent/history}HistoryRepresentativeDataType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryDataType", propOrder = {
    "historyPartnershipData",
    "historyRepresentativeData"
})
public class HistoryDataType {

    @XmlElement(name = "HistoryPartnershipData")
    protected HistoryPartnershipDataType historyPartnershipData;
    @XmlElement(name = "HistoryRepresentativeData")
    protected HistoryRepresentativeDataType historyRepresentativeData;

    /**
     * Gets the value of the historyPartnershipData property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryPartnershipDataType }
     *     
     */
    public HistoryPartnershipDataType getHistoryPartnershipData() {
        return historyPartnershipData;
    }

    /**
     * Sets the value of the historyPartnershipData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryPartnershipDataType }
     *     
     */
    public void setHistoryPartnershipData(HistoryPartnershipDataType value) {
        this.historyPartnershipData = value;
    }

    /**
     * Gets the value of the historyRepresentativeData property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryRepresentativeDataType }
     *     
     */
    public HistoryRepresentativeDataType getHistoryRepresentativeData() {
        return historyRepresentativeData;
    }

    /**
     * Sets the value of the historyRepresentativeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryRepresentativeDataType }
     *     
     */
    public void setHistoryRepresentativeData(HistoryRepresentativeDataType value) {
        this.historyRepresentativeData = value;
    }

}
