//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryRecordKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="HistoryRecordKindType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ADDRESS_NAME_CHANGE"/&gt;
 *     &lt;enumeration value="NEW_RECORD_CREATED"/&gt;
 *     &lt;enumeration value="RECORD_RENEWED"/&gt;
 *     &lt;enumeration value="ACTIVE_RECORD_CHANGED"/&gt;
 *     &lt;enumeration value="RECORD_TEMPORARY_INACTIVATED"/&gt;
 *     &lt;enumeration value="RECORD_INVALIDATED"/&gt;
 *     &lt;enumeration value="CORRECTION_PUBLIC_DETAILS"/&gt;
 *     &lt;enumeration value="CORRECTION_PRIVATE_DETAILS"/&gt;
 *     &lt;enumeration value="CORRECTION_RECORD_MERGE"/&gt;
 *     &lt;enumeration value="DELETE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "HistoryRecordKindType")
@XmlEnum
public enum HistoryRecordKindType {

    ADDRESS_NAME_CHANGE,
    NEW_RECORD_CREATED,
    RECORD_RENEWED,
    ACTIVE_RECORD_CHANGED,
    RECORD_TEMPORARY_INACTIVATED,
    RECORD_INVALIDATED,
    CORRECTION_PUBLIC_DETAILS,
    CORRECTION_PRIVATE_DETAILS,
    CORRECTION_RECORD_MERGE,
    DELETE;

    public String value() {
        return name();
    }

    public static HistoryRecordKindType fromValue(String v) {
        return valueOf(v);
    }

}
