//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryGroundType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryGroundType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HistoryGroundCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HistoryGroundDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryGroundType", propOrder = {
    "historyGroundCode",
    "historyGroundDescription"
})
public class HistoryGroundType {

    @XmlElement(name = "HistoryGroundCode")
    protected String historyGroundCode;
    @XmlElement(name = "HistoryGroundDescription")
    protected String historyGroundDescription;

    /**
     * Gets the value of the historyGroundCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistoryGroundCode() {
        return historyGroundCode;
    }

    /**
     * Sets the value of the historyGroundCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistoryGroundCode(String value) {
        this.historyGroundCode = value;
    }

    /**
     * Gets the value of the historyGroundDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistoryGroundDescription() {
        return historyGroundDescription;
    }

    /**
     * Sets the value of the historyGroundDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistoryGroundDescription(String value) {
        this.historyGroundDescription = value;
    }

}
