//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryRecordType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HistoryRecordKind" type="{http://www.bpo.bg/schema/represent/history}HistoryRecordKindType" minOccurs="0"/&gt;
 *         &lt;element name="HistoryRecordData" type="{http://www.bpo.bg/schema/represent/history}HistoryRecordDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryRecordType", propOrder = {
    "historyRecordKind",
    "historyRecordData"
})
public class HistoryRecordType {

    @XmlElement(name = "HistoryRecordKind")
    @XmlSchemaType(name = "token")
    protected HistoryRecordKindType historyRecordKind;
    @XmlElement(name = "HistoryRecordData")
    protected HistoryRecordDataType historyRecordData;

    /**
     * Gets the value of the historyRecordKind property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryRecordKindType }
     *     
     */
    public HistoryRecordKindType getHistoryRecordKind() {
        return historyRecordKind;
    }

    /**
     * Sets the value of the historyRecordKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryRecordKindType }
     *     
     */
    public void setHistoryRecordKind(HistoryRecordKindType value) {
        this.historyRecordKind = value;
    }

    /**
     * Gets the value of the historyRecordData property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryRecordDataType }
     *     
     */
    public HistoryRecordDataType getHistoryRecordData() {
        return historyRecordData;
    }

    /**
     * Sets the value of the historyRecordData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryRecordDataType }
     *     
     */
    public void setHistoryRecordData(HistoryRecordDataType value) {
        this.historyRecordData = value;
    }

}
