//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryRecordDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryRecordDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HistoryGrounds" type="{http://www.bpo.bg/schema/represent/history}HistoryGroundType" minOccurs="0"/&gt;
 *         &lt;element name="HistoryOldData" type="{http://www.bpo.bg/schema/represent/history}HistoryDataType" minOccurs="0"/&gt;
 *         &lt;element name="HistoryNewData" type="{http://www.bpo.bg/schema/represent/history}HistoryDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryRecordDataType", propOrder = {
    "historyGrounds",
    "historyOldData",
    "historyNewData"
})
public class HistoryRecordDataType {

    @XmlElement(name = "HistoryGrounds")
    protected HistoryGroundType historyGrounds;
    @XmlElement(name = "HistoryOldData")
    protected HistoryDataType historyOldData;
    @XmlElement(name = "HistoryNewData")
    protected HistoryDataType historyNewData;

    /**
     * Gets the value of the historyGrounds property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryGroundType }
     *     
     */
    public HistoryGroundType getHistoryGrounds() {
        return historyGrounds;
    }

    /**
     * Sets the value of the historyGrounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryGroundType }
     *     
     */
    public void setHistoryGrounds(HistoryGroundType value) {
        this.historyGrounds = value;
    }

    /**
     * Gets the value of the historyOldData property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryDataType }
     *     
     */
    public HistoryDataType getHistoryOldData() {
        return historyOldData;
    }

    /**
     * Sets the value of the historyOldData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryDataType }
     *     
     */
    public void setHistoryOldData(HistoryDataType value) {
        this.historyOldData = value;
    }

    /**
     * Gets the value of the historyNewData property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryDataType }
     *     
     */
    public HistoryDataType getHistoryNewData() {
        return historyNewData;
    }

    /**
     * Sets the value of the historyNewData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryDataType }
     *     
     */
    public void setHistoryNewData(HistoryDataType value) {
        this.historyNewData = value;
    }

}
