//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryPartnershipDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryPartnershipDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PartnershipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnershipType" type="{http://www.bpo.bg/schema/represent/history}PartnershipType" minOccurs="0"/&gt;
 *         &lt;element name="FormattedNameAddress" type="{http://www.bpo.bg/schema/represent/history}FormattedNameAddressType" minOccurs="0"/&gt;
 *         &lt;element name="NationalNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnershipRepresentativeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnershipRepresentativeKind" type="{http://www.bpo.bg/schema/represent/history}PartnershipRepresentativeKindType" minOccurs="0"/&gt;
 *         &lt;element name="IpObjects" type="{http://www.bpo.bg/schema/represent/history}IpObjectsType" minOccurs="0"/&gt;
 *         &lt;element name="OriCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OriRepresentativesNames" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnershipMembers" type="{http://www.bpo.bg/schema/represent/history}PartnershipMembersType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryPartnershipDataType", propOrder = {
    "partnershipCode",
    "partnershipType",
    "formattedNameAddress",
    "nationalNumber",
    "partnershipRepresentativeName",
    "partnershipRepresentativeKind",
    "ipObjects",
    "oriCountryCode",
    "oriRepresentativesNames",
    "partnershipMembers"
})
public class HistoryPartnershipDataType {

    @XmlElement(name = "PartnershipCode")
    protected String partnershipCode;
    @XmlElement(name = "PartnershipType")
    @XmlSchemaType(name = "token")
    protected PartnershipType partnershipType;
    @XmlElement(name = "FormattedNameAddress")
    protected FormattedNameAddressType formattedNameAddress;
    @XmlElement(name = "NationalNumber")
    protected String nationalNumber;
    @XmlElement(name = "PartnershipRepresentativeName")
    protected String partnershipRepresentativeName;
    @XmlElement(name = "PartnershipRepresentativeKind")
    @XmlSchemaType(name = "token")
    protected PartnershipRepresentativeKindType partnershipRepresentativeKind;
    @XmlElement(name = "IpObjects")
    @XmlSchemaType(name = "token")
    protected IpObjectsType ipObjects;
    @XmlElement(name = "OriCountryCode")
    protected String oriCountryCode;
    @XmlElement(name = "OriRepresentativesNames")
    protected String oriRepresentativesNames;
    @XmlElement(name = "PartnershipMembers")
    protected PartnershipMembersType partnershipMembers;

    /**
     * Gets the value of the partnershipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnershipCode() {
        return partnershipCode;
    }

    /**
     * Sets the value of the partnershipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnershipCode(String value) {
        this.partnershipCode = value;
    }

    /**
     * Gets the value of the partnershipType property.
     * 
     * @return
     *     possible object is
     *     {@link PartnershipType }
     *     
     */
    public PartnershipType getPartnershipType() {
        return partnershipType;
    }

    /**
     * Sets the value of the partnershipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnershipType }
     *     
     */
    public void setPartnershipType(PartnershipType value) {
        this.partnershipType = value;
    }

    /**
     * Gets the value of the formattedNameAddress property.
     * 
     * @return
     *     possible object is
     *     {@link FormattedNameAddressType }
     *     
     */
    public FormattedNameAddressType getFormattedNameAddress() {
        return formattedNameAddress;
    }

    /**
     * Sets the value of the formattedNameAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormattedNameAddressType }
     *     
     */
    public void setFormattedNameAddress(FormattedNameAddressType value) {
        this.formattedNameAddress = value;
    }

    /**
     * Gets the value of the nationalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalNumber() {
        return nationalNumber;
    }

    /**
     * Sets the value of the nationalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalNumber(String value) {
        this.nationalNumber = value;
    }

    /**
     * Gets the value of the partnershipRepresentativeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnershipRepresentativeName() {
        return partnershipRepresentativeName;
    }

    /**
     * Sets the value of the partnershipRepresentativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnershipRepresentativeName(String value) {
        this.partnershipRepresentativeName = value;
    }

    /**
     * Gets the value of the partnershipRepresentativeKind property.
     * 
     * @return
     *     possible object is
     *     {@link PartnershipRepresentativeKindType }
     *     
     */
    public PartnershipRepresentativeKindType getPartnershipRepresentativeKind() {
        return partnershipRepresentativeKind;
    }

    /**
     * Sets the value of the partnershipRepresentativeKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnershipRepresentativeKindType }
     *     
     */
    public void setPartnershipRepresentativeKind(PartnershipRepresentativeKindType value) {
        this.partnershipRepresentativeKind = value;
    }

    /**
     * Gets the value of the ipObjects property.
     * 
     * @return
     *     possible object is
     *     {@link IpObjectsType }
     *     
     */
    public IpObjectsType getIpObjects() {
        return ipObjects;
    }

    /**
     * Sets the value of the ipObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpObjectsType }
     *     
     */
    public void setIpObjects(IpObjectsType value) {
        this.ipObjects = value;
    }

    /**
     * Gets the value of the oriCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriCountryCode() {
        return oriCountryCode;
    }

    /**
     * Sets the value of the oriCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriCountryCode(String value) {
        this.oriCountryCode = value;
    }

    /**
     * Gets the value of the oriRepresentativesNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriRepresentativesNames() {
        return oriRepresentativesNames;
    }

    /**
     * Sets the value of the oriRepresentativesNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriRepresentativesNames(String value) {
        this.oriRepresentativesNames = value;
    }

    /**
     * Gets the value of the partnershipMembers property.
     * 
     * @return
     *     possible object is
     *     {@link PartnershipMembersType }
     *     
     */
    public PartnershipMembersType getPartnershipMembers() {
        return partnershipMembers;
    }

    /**
     * Sets the value of the partnershipMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnershipMembersType }
     *     
     */
    public void setPartnershipMembers(PartnershipMembersType value) {
        this.partnershipMembers = value;
    }

}
