//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IpObjectsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="IpObjectsType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="MARKS_GEO_INDICATIONS_DESIGNS"/&gt;
 *     &lt;enumeration value="PATENTS_UTILITY_MODELS"/&gt;
 *     &lt;enumeration value="BOTH"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IpObjectsType")
@XmlEnum
public enum IpObjectsType {

    MARKS_GEO_INDICATIONS_DESIGNS,
    PATENTS_UTILITY_MODELS,
    BOTH;

    public String value() {
        return name();
    }

    public static IpObjectsType fromValue(String v) {
        return valueOf(v);
    }

}
