//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.bpo.schema.represent.history package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _History_QNAME = new QName("http://www.bpo.bg/schema/represent/history", "History");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.bpo.schema.represent.history
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HistoryType }
     * 
     */
    public HistoryType createHistoryType() {
        return new HistoryType();
    }

    /**
     * Create an instance of {@link HistoryRecordType }
     * 
     */
    public HistoryRecordType createHistoryRecordType() {
        return new HistoryRecordType();
    }

    /**
     * Create an instance of {@link HistoryRecordDataType }
     * 
     */
    public HistoryRecordDataType createHistoryRecordDataType() {
        return new HistoryRecordDataType();
    }

    /**
     * Create an instance of {@link HistoryGroundType }
     * 
     */
    public HistoryGroundType createHistoryGroundType() {
        return new HistoryGroundType();
    }

    /**
     * Create an instance of {@link HistoryDataType }
     * 
     */
    public HistoryDataType createHistoryDataType() {
        return new HistoryDataType();
    }

    /**
     * Create an instance of {@link HistoryPartnershipDataType }
     * 
     */
    public HistoryPartnershipDataType createHistoryPartnershipDataType() {
        return new HistoryPartnershipDataType();
    }

    /**
     * Create an instance of {@link HistoryRepresentativeDataType }
     * 
     */
    public HistoryRepresentativeDataType createHistoryRepresentativeDataType() {
        return new HistoryRepresentativeDataType();
    }

    /**
     * Create an instance of {@link PartnershipMembersType }
     * 
     */
    public PartnershipMembersType createPartnershipMembersType() {
        return new PartnershipMembersType();
    }

    /**
     * Create an instance of {@link PartnershipMemberType }
     * 
     */
    public PartnershipMemberType createPartnershipMemberType() {
        return new PartnershipMemberType();
    }

    /**
     * Create an instance of {@link FormattedNameAddressType }
     * 
     */
    public FormattedNameAddressType createFormattedNameAddressType() {
        return new FormattedNameAddressType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HistoryType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bpo.bg/schema/represent/history", name = "History")
    public JAXBElement<HistoryType> createHistory(HistoryType value) {
        return new JAXBElement<HistoryType>(_History_QNAME, HistoryType.class, null, value);
    }

}
