//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.bpo.bg/schema/represent/history", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.duosoft.bpo.registers.nonentity.history.agent;
