//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartnershipMemberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnershipMemberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PartnershipMemberCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="PartnershipMemberName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnershipMemberType", propOrder = {
    "partnershipMemberCode",
    "partnershipMemberName"
})
public class PartnershipMemberType {

    @XmlElement(name = "PartnershipMemberCode")
    protected BigInteger partnershipMemberCode;
    @XmlElement(name = "PartnershipMemberName")
    protected String partnershipMemberName;

    /**
     * Gets the value of the partnershipMemberCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPartnershipMemberCode() {
        return partnershipMemberCode;
    }

    /**
     * Sets the value of the partnershipMemberCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPartnershipMemberCode(BigInteger value) {
        this.partnershipMemberCode = value;
    }

    /**
     * Gets the value of the partnershipMemberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnershipMemberName() {
        return partnershipMemberName;
    }

    /**
     * Sets the value of the partnershipMemberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnershipMemberName(String value) {
        this.partnershipMemberName = value;
    }

}
