//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 10:38:40 AM EET 
//


package bg.duosoft.bpo.registers.nonentity.history.agent;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartnershipRepresentativeKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PartnershipRepresentativeKindType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="MANAGER"/&gt;
 *     &lt;enumeration value="MEMBER"/&gt;
 *     &lt;enumeration value="SOLE_OWNER"/&gt;
 *     &lt;enumeration value="MEMBER_OF_MANAGEMENT_BOARD"/&gt;
 *     &lt;enumeration value="MEMBER_OF_BOARD_OF_DIRECTORS"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PartnershipRepresentativeKindType")
@XmlEnum
public enum PartnershipRepresentativeKindType {

    MANAGER,
    MEMBER,
    SOLE_OWNER,
    MEMBER_OF_MANAGEMENT_BOARD,
    MEMBER_OF_BOARD_OF_DIRECTORS,
    OTHER;

    public String value() {
        return name();
    }

    public static PartnershipRepresentativeKindType fromValue(String v) {
        return valueOf(v);
    }

}
