package bg.duosoft.bpo.common.security.util;

public interface SecurityRole {
    String ADMIN_PATENT_CLASSIFICATION_CPC = "ADMIN_PATENT_CLASSIFICATION_CPC";
    String ADMIN_PATENT_CLASSIFICATION_IPC = "ADMIN_PATENT_CLASSIFICATION_IPC";
    String ADMIN_PATENT_CLASSIFICATION_MISSING_CLASSES = "ADMIN_PATENT_CLASSIFICATION_MISSING_CLASSES";
    String ADMIN_PATENT_CLASSIFICATION_OLD_CLASS_VERSIONS = "ADMIN_PATENT_CLASSIFICATION_OLD_CLASS_VERSIONS";
    String WIPO_STATISTICS_ACCESS = "WIPO_STATISTICS_ACCESS";
    String EPO_MONTHLY_REPORTS_ACCESS = "EPO_MONTHLY_REPORTS_ACCESS";
    String AGENTS_ADMIN = "AGENTS_ADMIN";
    String TM_EXPORTER_ACCESS = "ROLE_TM_EXPORTER_ACCESS";
    String TM_EXPORTER_FULL_EXPORT = "ROLE_TM_EXPORTER_FULL_EXPORT";
    String ADMIN_REGISTERS = "ADMIN_REGISTERS";
    String ADMIN_PUBLIC_CORE = "ADMIN_PUBLIC_CORE";
    String IP_OBJECT_E_SERVICES_ADMIN = "IP_OBJECT_E_SERVICES_ADMIN";
    String ADMIN_CONSOLE_ACCESS = "ADMIN_CONSOLE_ACCESS";
    String USERS_ACCESS = "ROLE_USERS_ACCESS";
    String USERS_EDIT = "ROLE_USERS_EDIT";
    String CACHE_ACCESS = "ROLE_CACHE_ACCESS";
    String ADMIN_APP_DRAFTS = "ADMIN_APP_DRAFTS";
    String SIGNATURE_ADMIN = "ROLE_SIGNATURE_ADMIN";
}
